# frozen_string_literal: true

# Auto-generated by the pushto release workflow. DO NOT EDIT.
class Pushto < Formula
  desc "Deploy your projects to pushto.host from your terminal"
  homepage "https://pushto.host"
  version "0.4.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mydude-industries/homebrew-tap/releases/download/v0.4.5/pushto-0.4.5-darwin-arm64.tar.gz"
      sha256 "cefae6843a34dd97aa6dddca6d79632fe2b2cd077e485b8ac09ce7aa0906eee9"
    end
    on_intel do
      url "https://github.com/mydude-industries/homebrew-tap/releases/download/v0.4.5/pushto-0.4.5-darwin-amd64.tar.gz"
      sha256 "f8fffd7d900a2e6886c37028ebfbd92502ce882da960ae2f41738321cf5ca869"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mydude-industries/homebrew-tap/releases/download/v0.4.5/pushto-0.4.5-linux-arm64.tar.gz"
      sha256 "6d72c49dbef4f60104f1791c0f1aaa98b37e2c6706c4b73a437f44e3f75007a9"
    end
    on_intel do
      url "https://github.com/mydude-industries/homebrew-tap/releases/download/v0.4.5/pushto-0.4.5-linux-amd64.tar.gz"
      sha256 "bddea99c54dbecb01b72a2a708f6af35e3fd09025b881b8b72d2dabfdbf60037"
    end
  end

  def install
    bin.install "pushto"
  end

  test do
    system "#{bin}/pushto", "--version"
  end
end
